### ISSUE TITLE
Issues on Setup (Fixed)

### ISSUE THREAD

**Issue by evuvo-ke** [navariltd/frappe-mpsa-payments#8]
Thank you Navari for this script,

When setting up this module for the first time, the terminal command given is:
`$ bench --site [your-site-name] install-app frappe-mpsa-payments`

It should be 
`$ bench --site [your-site-name] install-app frappe_mpsa_payments`

**Comment by maniamartial** [comment]
Was resolved. Thank you for your insights.
We are marking this as resolved.
